// <auto-generated />
using System;
using Fiap.Api.MonitoramentoAmbiental.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.MonitoramentoAmbiental.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.AlertaModel", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_alerta");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("date")
                        .HasColumnName("data_hora");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo_alerta");

                    b.HasKey("AlertaId");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.ControleIrrigacaoModel", b =>
                {
                    b.Property<int>("ControleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_controle");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ControleId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("date")
                        .HasColumnName("data_hora");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("estado");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("localizacao");

                    b.Property<int>("PrevisaoChuvaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_previsao_chuva");

                    b.HasKey("ControleId");

                    b.HasIndex("PrevisaoChuvaId");

                    b.ToTable("ControleIrrigacoes", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.LeituraModel", b =>
                {
                    b.Property<int>("LeituraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_leitura");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeituraId"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("date")
                        .HasColumnName("data_hora");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    b.Property<decimal>("Valor")
                        .HasColumnType("float")
                        .HasColumnName("valor");

                    b.HasKey("LeituraId");

                    b.HasIndex("SensorId");

                    b.ToTable("Leituras", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.PrevisaoChuvaModel", b =>
                {
                    b.Property<int>("PrevisaoChuvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_previsao_chuva");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrevisaoChuvaId"));

                    b.Property<DateTime>("DataPrevisaoChuva")
                        .HasColumnType("date")
                        .HasColumnName("data_previsao");

                    b.Property<string>("Previsao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("previsao");

                    b.HasKey("PrevisaoChuvaId");

                    b.ToTable("PrevisoesChuva", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.SensorModel", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("localizacao");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("tipo_sensor");

                    b.HasKey("SensorId");

                    b.ToTable("Sensores", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.ControleIrrigacaoModel", b =>
                {
                    b.HasOne("Fiap.Api.MonitoramentoAmbiental.Model.PrevisaoChuvaModel", "PrevisaoChuva")
                        .WithMany()
                        .HasForeignKey("PrevisaoChuvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrevisaoChuva");
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.LeituraModel", b =>
                {
                    b.HasOne("Fiap.Api.MonitoramentoAmbiental.Model.SensorModel", "Sensor")
                        .WithMany("Leitura")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("Fiap.Api.MonitoramentoAmbiental.Model.SensorModel", b =>
                {
                    b.Navigation("Leitura");
                });
#pragma warning restore 612, 618
        }
    }
}
